name: CashControl Cloud Auto-Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4 # Passage à v4
      
      - name: ☕ Configuration de Java
        uses: actions/setup-java@v4 # Passage à v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: 🚀 Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true
          
      - name: 📦 Installation des dépendances
        run: flutter pub get
        
      - name: 🛠 Compilation de l'APK (Release)
        run: flutter build apk --release
        
      - name: 📤 Livraison de l'APK
        uses: actions/upload-artifact@v4 # CORRECTION : Passage à v4 ici
        with:
          name: CashControl-Cloud-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error # Sécurité : échoue si l'APK n'est pas trouvé
